routes/web.php
<?php

use RealRashid\SweetAlert\Facades\Alert;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
});

// Users & All Roles Control Panel Routes
Route::get('/home', [App\Http\Controllers\HomeController::class, 'indexUser'])->name('home');

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'middleware' => ['role:blogwritter|admin']], function () {
    Route::get('/dashboard', [AdminController::class, 'index'])->name('admin');
    Route::get('/profile', [AdminController::class, 'showProfile'])->name('profile');
    Route::get('/profile/{id}/edit', [AdminController::class, 'editProfile'])->name('edit.profile');
    Route::put('/profile/{id}/update', [AdminController::class, 'updateProfile'])->name('update.profile');

    //  Roles Control Admin, Blogwriter

    //  SoftDelete
    Route::get('/post/trashed', [App\Http\Controllers\PostController::class, 'trashed'])->name('trashed');
    Route::get('/post/restore/{id}', [App\Http\Controllers\PostController::class, 'restore'])->name('restored');
    Route::delete('/post/delete/{id}', [App\Http\Controllers\PostController::class, 'kill'])->name('forcedelete');

    //  Coments Post
    Route::post('/coments/{post}', 'CommentController@store')->name('comment.store');

    Route::resource('post', PostController::class);
    Route::resource('category', CategoryController::class);
    Route::resource('tag', TagController::class);
    
    //  Roles Control Admin,
    Route::resource('users', UsersController::class);
    Route::resource('permission', PermissionController::class);
    Route::resource('roles', RolesController::class);
});

// test iis aoliya//

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'password',
        'address',
        'phone',
        'photo',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts() {
        return $this->hasMany(Posts::class, 'user_id', 'id');
    }

    public function comments() {
        return $this->hasMany('App\Models\Comments');
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Role;
use App\Models\Permission;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\ModelNotFoundException; 

class UsersController extends Controller
{
    //

    public function __construct()
    {
        $this->middleware('role:owner|admin');
    }

    // Index Page for Users
    public function index(Request $request)
    {
        $users = User::paginate(7);
        
        $params = [
            'title' => 'Users Listing',
            'users' => $users,
        ];

        //Count permissions Roles  

        // $data = [];
        // $n_perms = User::query()
        //         ->withCount(['roles', 'permissions']);
        // $n_perms = User::query()->withCount(['roles', 'permissions']);
        // $n_perms = User::with(['roles', 'permissions'])->count();

        // $data = [
        //     'n_perms' => $n_perms,
        // ];

        return view('admin.users.users_list')->with('i', ($request->input('page', 1) - 1) * 5)->with($params);
    }

    // Create User Page
    public function create()
    {
        $roles = Role::all();

        $params = [
            'title' => 'Create User',
            'roles' => $roles,
        ];

        return view('admin.users.users_create')->with($params);
    }

    // Store New User
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'username' => ['required', 'string', 'min:2', 'max:255'],
            'address' => ['required', 'string', 'max:255'],
            'phone' => ['required', 'regex:/^((62)|(08))[0-9]/', 'not_regex:/[a-z]/', 'min:11', 'max:13'], //['required', 'regex:/^((+62)|(08))[0-9]+/', 'not_regex:/[a-z]/|min:11|max:13'],    //'required|regex:/^((+62)|(08))[0-9]/|not_regex:/[a-z]/|min:11|max:13',  
            'email' => 'required|unique:users',
            'password' => 'required',
            'photo' => 'sometimes|image|mimes:jpg,png,jpeg|max:9000',
        ]);

        $photo = $request->file('photo');
        $photo_name = time().'.'.$photo->getClientOriginalName();
        // $gambar->storeAs('images', $image_name, 'public');
        $photo->move(public_path('images/user/'),$photo_name);

        $user = User::create([
            'name' => $request->input('name'),
            'username' => $request['username'],
            'address' => $request['address'],
            'phone' => $request['phone'],
            'email' => $request->input('email'),
            'photo' => $photo_name,
            'password' => bcrypt($request->input('password')),
        ]);

        $role = Role::find($request->input('role_id'));

        $user->attachRole($role);
        

        return redirect()->route('users.index')->with('success', "The user $user->name has successfully been created.");
    }

    // Delete Confirmation Page
    public function show($id)
    {
        try {
            $user = User::findOrFail($id);

            $params = [
                'title' => 'Confirm Delete Record',
                'user' => $user,
            ];

            return view('admin.users.users_delete')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    // Editing User Information Page
    public function edit($id)
    {
        try {
            $user = User::findOrFail($id);

            //$roles = Role::all();
            $roles = Role::with('permissions')->get();
            $permissions = Permission::all();

            $params = [
                'title' => 'Edit User',
                'user' => $user,
                'roles' => $roles,
                'permissions' => $permissions,
            ];

            return view('admin.users.users_edit')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }

    // Update User Information to DB
    public function update(Request $request, $id)
    {
        // try {
            // $user = User::findOrFail($id);

            $this->validate($request, [
                'name' => 'required',
                'username' => ['required', 'string', 'min:2', 'max:255'],
                'address' => ['required', 'string', 'max:255'],
                'phone' => ['required', 'regex:/^((62)|(08))[0-9]/', 'not_regex:/[a-z]/', 'min:11', 'max:13'],
                'email' => 'required|email|unique:users,email,' . $id,
                // 'photo' => 'sometimes|image|mimes:jpg,png,jpeg|max:9000',
            ]);

            $user = User::findOrFail($id);
            if($request->hasFile('photo')){
                $photo = $request->file('photo');
                $photo_name = time().'.'.$photo->getClientOriginalName();
                $photo->move(public_path('images/user/'), $photo_name);


                    $user->name = $request->input('name');
                    $user->username = $request->input('username');
                    $user->address = $request->input('address');
                    $user->phone = $request->input('phone');
                    $user->email = $request->input('email');
                    // $user->password = bcrypt($request->input('password'));
                    $user->photo = $photo_name;
            } 
            else {
                $user->name = $request->input('name');
                $user->username = $request->input('username');
                $user->address = $request->input('address');
                $user->phone = $request->input('phone');
                $user->email = $request->input('email');
                // $user->password = bcrypt($request->input('password'));
            }

            // $user->name = $request->input('name');
            // $user->username = $request->input('username');
            // $user->address = $request->input('address');
            // $user->phone = $request->input('phone');
            // $user->email = $request->input('email');

            $user->save();

            // Update role of the user
            $roles = $user->roles;

            foreach ($roles as $key => $value) {
                $user->detachRole($value);
            }

            $role = Role::find($request->input('role_id'));

            $user->attachRole($role);

            // Update permission of the user
            //$permission = Permission::find($request->input('permission_id'));
            //$user->attachPermission($permission);

            return redirect()->route('users.index')->with('success', "$user->name has successfully been updated.");
        // } catch (ModelNotFoundException $ex) {
        //     if ($ex instanceof ModelNotFoundException) {
        //         return response()->view('errors.' . '404');
        //     }
        // }
    }

    // Remove User from DB with detaching Role
    public function destroy($id)
    {
        try {
            $user = User::findOrFail($id);

            // Detach from Role
            $roles = $user->roles;

            foreach ($roles as $key => $value) {
                $user->detachRole($value);
            }

            $user->delete();

            return redirect()->route('users.index')->with('success', "$user->name has successfully been archived.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }
}

resources/views/admin/users/users_create.blade.php
@extends('layouts.admin')
@section('sub-title', 'Users')
@section('location', 'Users / Create')
@push('links')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css"> 
@endpush
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <a href="{{route('users.index')}}" class="btn btn-info">Back</a>
                <h4 class="ml-3">{{$title}}</h4>
            </div>
            <div class="card-body">
                <form action="{{route('users.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} row">
                        <label for="name" class="col-sm-2 col-form-label">Name
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('name') ?: '' }}" id="name" name="name" placeholder="Enter name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('name'))
                            <span class="help-block">{{ $errors->first('name') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('username') ? ' has-error' : '' }} row">
                        <label for="username" class="col-sm-2 col-form-label">Username
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('username') ?: '' }}" id="username" name="username" placeholder="Enter username" class="form-control col-md-7 col-xs-12"> @if ($errors->has('username'))
                            <span class="help-block">{{ $errors->first('username') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('address') ? ' has-error' : '' }} row">
                        <label for="address" class="col-sm-2 col-form-label">Address
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('address') ?: '' }}" id="address" name="address" placeholder="Enter address" class="form-control col-md-7 col-xs-12"> @if ($errors->has('address'))
                            <span class="help-block">{{ $errors->first('address') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }} row">
                        <label for="phone" class="col-sm-2 col-form-label">Phone
                            <span class="required">* <span style="font-size: 10px; color:#a6a9b6">min:11|max:13</span></span>
                        </label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('phone') ?: '' }}" id="phone" name="phone" placeholder="Enter mobile number with prefix 08 or 62" class="form-control col-md-7 col-xs-12"> @if ($errors->has('phone'))
                            <span class="help-block" style="color: red">{{ $errors->first('phone') }}</span>
                            @endif
                        </div>
                    </div>
            
                    <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }} row">
                        <label for="email" class="col-sm-2 col-form-label">Email
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-10">
                            <input type="text" value="{{ Request::old('email') ?: '' }}" id="email" name="email" placeholder="Enter email" class="form-control col-md-7 col-xs-12"> @if ($errors->has('email'))
                            <span class="help-block">{{ $errors->first('email') }}</span>
                            @endif
                        </div>
                    </div>
            
                    <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }} row">
                        <label for="password" class="col-sm-2 col-form-label">Password
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-10">
                            <input type="password" value="{{ Request::old('password') ?: '' }}" id="password" name="password" placeholder="Enter password" class="form-control col-md-7 col-xs-12"> @if ($errors->has('password'))
                            <span class="help-block">{{ $errors->first('password') }}</span>
                            @endif
                        </div>
                    </div>
            
                    <div class="form-group{{ $errors->has('confirm_password') ? ' has-error' : '' }} row">
                        <label for="confirm_password" class="col-sm-2 col-form-label">Confirm Password
                            <span class="required">*</span>
                        </label>
                        <div class="col-sm-10">
                            <input type="password" value="{{ Request::old('confirm_password') ?: '' }}" id="confirm_password" placeholder="Enter confirm password" name="confirm_password"
                                class="form-control col-md-7 col-xs-12"> @if ($errors->has('confirm_password'))
                            <span class="help-block">{{ $errors->first('confirm_password') }}</span>
                            @endif
                        </div>
                    </div>
            
                    {{-- <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Role</label>
                        <div class="col-md-6 col-sm-6">
                          <div class="selectgroup w-100">
                            <label class="selectgroup-item">
                              <input type="radio" name="value" value="developer" class="selectgroup-input">
                              <span class="selectgroup-button">Owner</span>
                            </label>
                            <label class="selectgroup-item">
                              <input type="radio" name="value" value="ceo" class="selectgroup-input">
                              <span class="selectgroup-button">Admin</span>
                            </label>
                            <label class="selectgroup-item">
                                <input type="radio" name="value" value="ceo" class="selectgroup-input">
                                <span class="selectgroup-button">Writter</span>
                              </label>
                          </div>
                        </div>
                    </div> --}}

                    <div class="form-group{{ $errors->has('role_id') ? ' has-error' : '' }} row">
                        <label class="col-sm-2 col-form-label" for="category_id">Role
                            <span class="required">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select class="selectpicker form-control" id="role_id" name="role_id">
                                <option value="" disabled selected>Select your role</option>
                                @if(count($roles)) @foreach($roles as $row)
                                <option value="{{$row->id}}">{{$row->name}}</option>
                                @endforeach @endif
                            </select>
                            @if ($errors->has('role_id'))
                            <span class="help-block">{{ $errors->first('role_id') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Avatar</label>
                        <div class="col-sm-10">
                            <input type="file" class="form-control col-md-7 col-xs-12" name="photo" onchange="previewFile(this)" />
                            <img id="previewImg" src="" alt="" style="max-width: 130px;margin-top: 20px;max-height: 130px;" />
                        </div>
                    </div>
            
                    <div class="ln_solid"></div>
            
                    <div class="form-group">
                        <div class="col-sm-2 col-form-label text-md-right">
                            <input type="hidden" name="_token" value="{{ Session::token() }}">
                            <button type="submit" class="btn btn-primary">Create User</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{{-- <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"> --}}

    {{-- <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Users</h1>
    </div>
    <a class="btn btn-sm btn-primary" href="{{route('users.index')}}">Back</a>
    <h2>{{$title}}</h2>
    <form method="post" action="{{ route('users.store') }}" data-parsley-validate class="form-horizontal form-label-left">

        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} row">
            <label for="name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" value="{{ Request::old('name') ?: '' }}" id="name" name="name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('name'))
                <span class="help-block">{{ $errors->first('name') }}</span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }} row">
            <label for="email" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input type="text" value="{{ Request::old('email') ?: '' }}" id="email" name="email" class="form-control col-md-7 col-xs-12"> @if ($errors->has('email'))
                <span class="help-block">{{ $errors->first('email') }}</span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }} row">
            <label for="password" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
                <input type="password" value="{{ Request::old('password') ?: '' }}" id="password" name="password" class="form-control col-md-7 col-xs-12"> @if ($errors->has('password'))
                <span class="help-block">{{ $errors->first('password') }}</span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('confirm_password') ? ' has-error' : '' }} row">
            <label for="confirm_password" class="col-sm-2 col-form-label">Confirm Password</label>
            <div class="col-sm-10">
                <input type="password" value="{{ Request::old('confirm_password') ?: '' }}" id="confirm_password" name="confirm_password"
                    class="form-control col-md-7 col-xs-12"> @if ($errors->has('confirm_password'))
                <span class="help-block">{{ $errors->first('confirm_password') }}</span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('role_id') ? ' has-error' : '' }} row">
            <label class="col-sm-2 col-form-label" for="category_id">Role
                <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <select class="form-control" id="role_id" name="role_id">
                    @if(count($roles)) @foreach($roles as $row)
                    <option value="{{$row->id}}">{{$row->name}}</option>
                    @endforeach @endif
                </select>
                @if ($errors->has('role_id'))
                <span class="help-block">{{ $errors->first('role_id') }}</span>
                @endif
            </div>
        </div>

        <div class="ln_solid"></div>

        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <input type="hidden" name="_token" value="{{ Session::token() }}">
                <button type="submit" class="btn btn-success">Create User</button>
            </div>
        </div>
    </form>
</main> 
</div>
</div> --}}

@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
@endpush

resources/views/admin/users/users_delete.blade.php
@extends('layouts.admin')
@section('sub-title', 'Users')
@section('location', 'Users / Delete')
@section('content')

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <a class="btn btn-sm btn-primary" href="{{route('users.index')}}">Back</a>
                    <h4 class="ml-3">{{$title}}</h4>
                </div>
                {{-- <div class="clearfix"></div> --}}
                <div class="card-body">
                    <p><i>Are you sure you want to delete <strong><u>{{$user->name}}</u></strong>?</i></p>

                    <form method="POST" action="{{ route('users.destroy', $user->id) }}">
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">Yes I'm sure. Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/users_list.blade.php
@extends('layouts.admin')
@section('sub-title', 'Users')
@section('location', 'Users')
@section('content')
  
      <div class="clearfix mt-4">
        <a href="{{route('users.create')}}" class="btn btn-info mb-2">Add User</a>
      </div>
      <div class="card">
        <div class="card-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">No</th>
                <th scope="col">Username</th>
                <th scope="col">Email</th>
                <th scope="col">Role</th>
                {{-- <th scope="col">Permissions</th> --}}
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
                @foreach($users as $user)
                    <tr>
                      <td>{{ ++$i }}</td>
                      <td>{{ $user->name }}</td>
                      <td>{{ $user->email }}</td>
                      <td>
                      @foreach($user->roles as $r)
                          {{$r->display_name}}
                      @endforeach
                      </td>
                      {{-- <td> --}}
                        {{-- {{$n_perms}} --}}
                        {{-- @foreach($user->permissions as $p)
                          {{$p->Count}}
                        @endforeach --}}
                      {{-- </td> --}}
                      <td>
                          {{-- <form action="{{ route('users.show', $user->id) }}" method="POST">
                              @csrf
                              @method('delete')
                              <a href="{{ route('users.edit', $user->id) }}" class="btn btn-primary btn-action " data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i></a>
                              <button type="submit" class="btn btn-danger btn-action" data-toggle="tooltip" title="Delete"><i class="fas fa-trash-alt"></i></button>
                            </form> --}}
                        <div>
                            <a class="btn btn-primary" href="{{ route('users.edit', $user->id) }}" class="btn btn-info" data-toggle="tooltip" title="Edit"><i class="fas fa-edit"></i> </a>
                            <a class="btn btn-danger" href="{{ route('users.show', $user->id) }}" class="btn btn-danger" data-toggle="tooltip" title="Delete"><i class="fas fa-trash-alt"></i> </a>
                        </div>
                      </td>
                    </tr>
                    @endforeach
            </tbody>
          </table>
          <!-- Pager -->
          <div class="clearfix mt-4">
            {{$users->links('vendor.pagination.bootstrap-4')}}
          </div>
        </div>
      </div>
@endsection